### ISSUE TITLE
php-working-form

### ISSUE THREAD

**Issue by mosespace** [mosespace/mosespace.github.io#2]
Hello everyone someone who can help me out with a working **`contact.php`** form, that will be appreciated.
Thank You

**Comment by wyntonfranklin** [comment]
hi @mosespace, I can create a simple one for you.

**Comment by mosespace** [comment]
> hi @mosespace, I can create a simple one for you.

Hi, I will be glad

**Comment by mosespace** [comment]
this was resolved under this pull request #17
